create table building (
    id bigint generated by default as identity,
    building_name varchar(255),
    city varchar(255),
    street varchar(255),
    zipcode varchar(255),
    basement_floor integer,
    ground_floor integer,
    primary key (id)
);
alter table building
    add constraint UIX_BUILDING_ADDRESS unique (zipcode, street, city, building_name);


create table contact (
    id bigint generated by default as identity,
    company varchar(255),
    mobile varchar(255),
    name varchar(255),
    primary key (id)
);
alter table contact
    add constraint UIX_CONTACT_NAME_MOBILE unique (name, mobile);


create table building_contact (
    building_id bigint not null,
    contact_id bigint not null,
    director varchar(255),
    primary key (building_id, contact_id)
);
alter table building_contact
    add constraint FK_CONTACT_ID
    foreign key (contact_id)
    references contact;
alter table building_contact
    add constraint FK_BUILDING_ID
    foreign key (building_id)
    references building;


create table office (
    id bigint generated by default as identity,
    building_id bigint not null,
    item_deal varchar(255),
    item_type varchar(255),
    target_floor_from integer,
    target_floor_note varchar(255),
    target_floor_to integer,
    primary key (id)
);


insert into building(id, building_name, city, street, zipcode, basement_floor, ground_floor) values(1, '국회도서관', '서울시', '서울특별시 영등포구 의사당대로 1', '12345', 5, 1);
insert into building(id, building_name, city, street, zipcode, basement_floor, ground_floor) values(2, '카카오 스페이스닷원', '서울시', '제주특별자치도 제주시 첨단로 242', '63309', 3, 0);

insert into contact(id, company, mobile, name) values(1, 'google', '010-1234-5678', '구글');
insert into contact(id, company, mobile, name) values(2, 'facebook', '010-2345-6789', '페이스북');
insert into contact(id, company, mobile, name) values(3, 'twitter', '010-3456-7890', '트위터');
insert into contact(id, company, mobile, name) values(4, 'daum', '010-4567-8901', '다음');


insert into building_contact(building_id, contact_id, director) values(1, 1, '건물주');
insert into building_contact(building_id, contact_id, director) values(1, 2, '임대인');
insert into building_contact(building_id, contact_id, director) values(2, 3, '건물주');

insert into office (id, building_id, item_deal, item_type, target_floor_from, target_floor_to, target_floor_note) values(1, 1, '임대', '사무실', 1,  null, '전체');